### ISSUE TITLE
./installer.sh: line 1: $'\r': command not found

### ISSUE THREAD

**Issue by MSoumen** [Feliz-SZK/Berserk#1]
Hey there, using WSL 1 when I ran `sudo chmod +x installer.sh`  It does nothing. And when trying to ran `sudo ./installer.sh` it throws some errors like:

> ./installer.sh: line 1: $'\r': command not found
>./installer.sh: line 2: $'\r': command not found
>./installer.sh: line 3: $'\r': command not found
>./installer.sh: line 38: syntax error: unexpected end of file

Please give some looks on it. Thank You

**Comment by Feliz-SZK** [comment]
can you check if ``apt`` is working or not?

**Comment by Feliz-SZK** [comment]
if yes then you woulda run ```bash installer.sh```

although couldn't grantee if it is gonna work on wsl

**Comment by Feliz-SZK** [comment]
well bro, wsl could be a ninny sometimes

type in `` sudo apt install dos2unix``

then,

``dos2unix installer.sh``

**Comment by MSoumen** [comment]
Thanks buddy 👍 this working 👍🙌
